# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GLMProbs <- function(X, Y) {
    .Call('_MGFRTest_GLMProbs', PACKAGE = 'MGFRTest', X, Y)
}

PermGLMProbs <- function(X, Y0) {
    .Call('_MGFRTest_PermGLMProbs', PACKAGE = 'MGFRTest', X, Y0)
}

